#!/bin/bash
nvenc(){
  echo "START"
  slop=$(slop -f "%x %y %w %h %g %i") && read -r X Y W H G ID < <(echo $slop)
  echo " rec" > /home/bresilla/.config/rec &
  prime-run ffmpeg -y -re \
    -f x11grab \
    -s "$W"x"$H" \
    -i :0.0+$X,$Y \
    -r 30 -framerate 60 \
    -vcodec h264_nvenc \
    -profile:v high444p -pixel_format yuv444p -qmin 10 -qmax 52 -preset lossless -level 51\
    /home/bresilla/temp/rec_$(date +%s).mp4
  echo "" > /home/bresilla/.config/rec
}

libx264(){
  slop=$(slop -f "%x %y %w %h %g %i") && read -r X Y W H G ID < <(echo $slop)
  echo " rec" > /home/bresilla/.config/rec &
  ffmpeg -y -re \
    -f x11grab \
    -s "$W"x"$H" \
    -i :0.0+$X,$Y \
    -vcodec libx264rgb \
    -profile:v high444 -pixel_format yuv444p -crf 19 -preset ultrafast -qp 0 -level 51\
    /home/bresilla/temp/rec_$(date +%s).mp4
  echo "" > /home/bresilla/.config/rec
    # -f alsa -i pulse \
}

if [ "$1" == "-w" ] ;then
    ffmpeg -f video4linux2 -s 1280x720 -i /dev/video$2 /home/bresilla/temp/cam$2_$(date +%s).mp4
elif [ "$1" == "-c" ] ;then
    libx264
elif [ "$1" == "-g" ] ;then
    nvenc
fi
