#!/bin/bash
source /home/bresilla/.cache/wal/colors.sh
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -theme-str "*{accent: ${color1:-#FFFFFF}; bckgrd: ${color0:-#000000};}")
BROWSER=firefox

srch=search
mark=bookmarks
hist=history

another=$(echo "\
$hist
$mark
$srch\
" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "search: ")


if [ "$another" == "$srch" ] ; then
	surfraw -browser=$BROWSER $(sr -elvi | awk -F'-' '{print $1}' | sed '/:/d' | awk '{$1=$1};1' | rofi "${ROFI_OPTIONS[@]}" -kb-row-select 'Tab' -kb-row-tab 'Control+space' -dmenu -i -p 'bangs: ')

elif [ "$another" == "$hist" ] ; then
    exec /home/bresilla/.config/rofi/menu/fox

elif [ "$another" == "$mark" ] ; then
    LINK=$(buku --nc -p -f 4 | awk -F'\t' '{print $1 "\t\t\t\t" $3 "\t\t" $4 "\t\t" $2}' | tail -n +2 | column -t -s $'\t' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p 'buku: ' | sed 's/ .*//;s/[^0-9]//g') 
    [[ -z $LINK ]] && exit 1
    buku -o $LINK

elif [ -z "$another" ] ; then
    #https://github.com/BelkaDev/RofiFtw
    handler=$(dirname $0)/duckduck
    rofi "${ROFI_OPTIONS[@]}" -modi blocks -show blocks -blocks-wrap $handler -display-blocks "SEARCH" 2>/dev/null
    [ -f "/tmp/ddgrofi.tmp" ] && $BROWSER "https://duckduckgo.com/?q=$(cat "/tmp/ddgrofi.tmp")" || exit 0

else
	$BROWSER "https://duckduckgo.com/?q=$another"
    #exec nohup $another > /dev/null 2>&1 &
fi
