#!/bin/bash
source ~/.cache/wal/colors.sh
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -theme-str "*{accent: ${color1:-#FFFFFF}; bckgrd: ${color0:-#000000};}")
edit_with="kitty --class=til"

another=$(echo "CONFIGS
ALIASES
SCRIPTS
ROFMENU
PROFILE" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "CONFIGS: ")

browse(){
	selected=$(ls -A --group-directories-first "$1/" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "$1: ")
	[[ -z $selected ]] && exit
	if [[ -f $1/$selected ]]; then
		$edit_with -e nvim $1/$selected
	elif [[ -d $1/$selected ]]; then
		browse $1/$selected
	else
		touch $1/$selected
		chmod +x $1/$selected
		$edit_with -e nvim $1/$selected
	fi
}

if [ "$another" == "PROFILE" ] ; then
	selected=$(echo "$HOME/dots/.zshrc
$HOME/dots/.bashrc
$HOME/dots/.profile
$HOME/dots/.other/variables
$HOME/dots/.config/git/config
$HOME/dots/.config/tmux/tmux.conf
$HOME/dots/.config/nixpkgs/home.nix" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "shell: ")
[[ -z $selected ]] && exit
	$edit_with -e nvim $selected

elif [ "$another" == "CONFIGS" ] ; then
	browse /home/bresilla/dots/.config;

elif [ "$another" == "SCRIPTS" ] ; then
    browse /home/bresilla/dots/.func;

elif [ "$another" == "ALIASES" ] ; then
	browse /home/bresilla/dots/.alias;

elif [ "$another" == "ROFMENU" ] ; then
	browse /home/bresilla/dots/.config/rofi/menu;

else
    echo $another
fi
