#!/usr/bin/env bash
source ~/.cache/wal/colors.sh
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -theme-str "*{accent: ${color6:-#FFFFFF}; bckgrd: ${color0:-#000000};}")

NOTE=$(dnote view | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p 'notes: ' | awk '{print $2}');
[[ -z $NOTE ]] && exit 1
PAGE=$(dnote view $NOTE | tail -n+2 | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p 'pages: ' | awk '{print $1}' | cut -d "(" -f2 | cut -d ")" -f1);
[[ -z $PAGE ]] && exit 1
kitty -e dnote edit $NOTE $PAGE
