#!/bin/bash
PADDINGS="40% 0 0 40%"
source ~/.cache/wal/colors.sh
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_icon -theme-str "*{accent: ${color1:-#FFFFFF}; spacing: $PADDINGS;}")

zoom=""
theme=""
record=""
screenshot=""

options="$zoom\n$theme\n$record\n$screenshot"
chosen="$(echo -e "$options" | rofi "${ROFI_OPTIONS[@]}" -dmenu -selected-row 2)"

PADDINGS="40% 0 0 46%"
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_icon -theme-str "*{accent: ${FOREGROUND:-#000000}; spacing: $PADDINGS;}")

case $chosen in
    $zoom)
        disp=$(echo -e "\n" | rofi "${ROFI_OPTIONS[@]}" -dmenu -selected-row 2)
        sleep .2
        if [ "$disp" == "" ] ; then
            slop -r boxzoom
        elif [ "$disp" == "" ] ; then
            slop -r crosshair
        fi
        ;;
    $theme)
        # pastel pick | pastel format hex | xclip -sel clip
        # xcolor | xclip -sel clip
        disp=$(echo -e "\n" | rofi "${ROFI_OPTIONS[@]}" -dmenu -selected-row 2)
        sleep .2
        if [ "$disp" == "" ] ; then
            sed -i '5s/.*/do wal -i $file --saturate 0.5/' /home/bresilla/.sbin/loopwall && systemctl --user restart wallpaper.service
        elif [ "$disp" == "" ] ; then
            sed -i '5s/.*/do wal -l -i $file --saturate 0.5/' /home/bresilla/.sbin/loopwall && systemctl --user restart wallpaper.service
        fi
        ;;
    $record)
        disp=$(echo -e "\n" | rofi "${ROFI_OPTIONS[@]}" -dmenu -selected-row 2)
        if [ "$disp" == "" ] ; then
            exec /home/bresilla/.sbin/recffm -w
        elif [ "$disp" == "" ] ; then
            killall ffmpeg
            exec /home/bresilla/.sbin/recffm -g
        fi
        ;;
    $screenshot)
        disp=$(echo -e "\n" | rofi "${ROFI_OPTIONS[@]}" -dmenu -selected-row 2)
        if [ "$disp" == "" ] ; then
            filename=/home/bresilla/temp/$(date +%s).png
        elif [ "$disp" == "" ] ; then
            filename=/tmp/$(date +%s).png
        fi
        maim -s | tee $filename | xclip -sel clip -t image/png -i && sxiv $filename
        ;;
esac
