#!/bin/bash
PADDINGS="40% 0 0 42%"
source /home/bresilla/.cache/wal/colors.sh
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_icon -theme-str "*{accent: ${color1:-#FFFFFF}; spacing: $PADDINGS;}")

monitor="M"
theme="T"
picker="P"
record="R"

options="$monitor\n$theme\n$record\n$picker"
chosen="$(echo -e "$options" | rofi "${ROFI_OPTIONS[@]}" -dmenu -selected-row 2)"

PADDINGS="40% 0 0 46%"
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_icon -theme-str "*{accent: ${FOREGROUND:-#000000}; spacing: $PADDINGS;}")

case $chosen in
    $monitor)
         disp=$(echo -e "1\n2" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "Select layout:")
        if [ "$disp" == "1" ] ; then
            exec xrandr --output "eDP-1" --primary --mode 3840x2160 --pos 0x0 --output "DP1" --off
        elif [ "$disp" == "2" ] ; then
            exec xrandr --output "eDP-1" --primary --mode 3840x2160 --pos 0x1080 --output "DP1" --mode 1920x1080 --pos 920x0
        fi
        ;;
    $picker)
        /home/bresilla/dots/.func/wm/rainbow $(cat /tmp/theme) pick
        . "${HOME}/.cache/wal/colors.sh"
        /home/bresilla/dots/.func/wm/colvim
        bspc config focused_border_color $color1 &
        /home/bresilla/dots/.func/wm/coltty &
        python /home/bresilla/.local/bin/pywalfox update &
        ;;
    $theme)
        if [ $(cat /tmp/theme) == "light" ] ; then
            echo dark > /tmp/theme
            /home/bresilla/dots/.func/wm/rainbow $(cat /tmp/theme)
        else
            echo light > /tmp/theme
            /home/bresilla/dots/.func/wm/rainbow $(cat /tmp/theme)
        fi
        . "${HOME}/.cache/wal/colors.sh"
        /home/bresilla/dots/.func/wm/colvim
        bspc config focused_border_color $color1 &
        /home/bresilla/dots/.func/wm/coltty &
        python /home/bresilla/.local/bin/pywalfox update &
        ;;
    $record)
        disp=$(echo -e "\n" | rofi "${ROFI_OPTIONS[@]}" -dmenu -selected-row 2)
        if [ "$disp" == "" ] ; then
            exec /home/bresilla/.func/media/capture -w
        elif [ "$disp" == "" ] ; then
            killall ffmpeg
            exec /home/bresilla/.func/media/capture -g
        fi
        ;;
esac
