#!/bin/bash
source /home/bresilla/.cache/wal/colors.sh
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -theme-str "*{accent: ${color1:-#FFFFFF}; bckgrd: ${color0:-#000000};}")
edit_with="kitty --class=til"

proj=projects
file=documents
cont=contacts
locl=local
pass=password
clip=clipboard
note=notes
task=tasks
usem=applist
book=books

another=$(echo "$file
$pass
$note
$book
$cont
$clip
$task
$proj
$usem" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "search: ")

if [ "$another" == "$file" ] ; then
    /home/bresilla/.config/rofi/menu/locate

elif [ "$another" == "$task" ] ; then
    /home/bresilla/.config/rofi/menu/task

elif [ "$another" == "$book" ] ; then
    /home/bresilla/.config/rofi/menu/books

elif [ "$another" == "$note" ] ; then
    /home/bresilla/.config/rofi/menu/note

elif [ "$another" == "$locl" ] ; then
    exec /home/bresilla/.config/rofi/menu/marks $HOME/sets/.notes/localhost.wiki

elif [ "$another" == "$clip" ] ; then
    rofi "${ROFI_OPTIONS[@]}" -modi "clipboard:greenclip print" -show clipboard

elif [ "$another" == "$usem" ] ; then
    appname=$(cat /home/bresilla/.config/applist |  grep "\S" | rofi "${ROFI_OPTIONS[@]}" -threads 0 -dmenu -i -p 'apps:')
    thelink=$(echo $appname | cut -d'+' -f3 | tr -d ' ')
    [[ ! -n $appname ]] && exit
    regex='(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'
    [[ $thelink =~ $regex ]]&& firefox $thelink || $edit_with -e nvim ~/.config/applist

elif [ "$another" == "$cont" ] ; then
    exec /home/bresilla/.config/rofi/menu/contacts

elif [ "$another" == "$proj" ] ; then
    pather=$(/env/go/bin/proji ls | head -n-1 | tail -n+4 | cut -d "|" -f3-5 | tr "|" "\t" | rofi "${ROFI_OPTIONS[@]}" -threads 0 -dmenu -i -p 'projects:' | cut -f2)
    nameer=$(basename $pather)
    [[ $pather ]] && sed -e "s|.*root.*|    root: $pather|" -e "1cname: \"$nameer\"" /home/bresilla/.config/tmux/PRO.yml > /home/bresilla/.config/tmux/prot.yml && /env/cpp/bin/tmass -l /home/bresilla/.config/tmux load prot && kitty --class=til tmux attach -t $nameer
    # kitty --class=til tmux attach -t $nameer

elif [ "$another" == "$pass" ] ; then
    exec /home/bresilla/.config/rofi/menu/pass

elif [ -z "$another" ] ; then
	echo "variable empty" && exit 1

else
  exec nohup $another > /dev/null 2>&1 &
fi
