-- vimp = require('vimp')
vimp.bind('n',            '<C-Pagedown>',             [[:BufferNext<CR>]])
vimp.bind('n',            '<C-Pageup>',               [[:BufferPrevious<CR>]])
vimp.bind('n',            '<C-M-Pagedown>',           [[:BufferMoveNext<CR>]])
vimp.bind('n',            '<C-M-Pageup>',             [[:BufferMovePrevious<CR>]])
