#!/usr/bin/env bash
#sent color sequences to all ppts (most important piece of this script)
colors_to_tty(){
    for tt in /dev/pts/*; do
        re='^[0-9]+$'; [[ $(basename $tt) =~ $re ]] && /usr/bin/cat $HOME/.cache/wal/sequences > $tt;
    done
}


#apply all colors (or specific command) to nvim needs 'pip install neovim-remote' and 'lsof'
colors_to_nvim(){
    if command -v nvr &> /dev/null ; then
        for i in `pidof nvim`; do
            for e in `lsof -p "$i" | grep LISTEN | awk -v N=$9 '{print $9}'`; do
                /home/bresilla/.local/bin/nvr --nostart --servername $e -c ":lua mycolors(\"$(cat $HOME/.cache/wal/theme)\")" &
            done
        done
    else
        1>&2 printf "${col[1]}executable: ${col[3]}nvr${col[1]} is not fond in your \$PATH, install it with ${col[3]}'pip install neovim-remote'${col[0]}\n"
    fi
}


colors_to_tty &
colors_to_nvim &

bspc config focused_border_color $(cat $HOME/.cache/wal/colors | head -n 2 | tail -n 1) &
python /home/bresilla/.local/bin/pywalfox update &
