#!/usr/bin/env bash

python /home/bresilla/dots/.func/wm/colvim &

bspc config focused_border_color $(cat $HOME/.cache/wal/colors | head -n 2 | tail -n 1) &

python /home/bresilla/.local/bin/pywalfox update &
