#!/bin/sh

case "$1" in
-f)
    cat /home/bresilla/.cache/wal/colors.sh | grep foreground | cut -d"'" -f2
    ;;
-b)
    cat /home/bresilla/.cache/wal/colors.sh | grep background | cut -d"'" -f2
    ;;
*)
    echo "color [-b bacground] [-f foreground]"
    ;;
esac
