#!/usr/bin/env bash
while true
  do ls $1/* | sort -R | tail -$N | while read file
    feh --no-fehbg --bg-scale $file &
do wal -n -i $file --saturate 0.5
    /home/bresilla/dots/.func/wm/colors &
    sleep $2
  done
done
