#!/usr/bin/env bash

MONITOR1=eDP-1
MONITOR2_1=DVI-I-2-2
MONITOR2_2=DP-3-3
MONITOR3_1=DVI-I-1-1
MONITOR3_2=DP-3-1

xrandr --output $MONITOR1 --primary --size 3456x2160 --pos 184x1080 --rotate normal \
    --output $MONITOR2_1 --size 1920x1080 --pos 0x0 --rotate normal \
    --output $MONITOR2_2 --size 1920x1080 --pos 0x0 --rotate normal \
    --output $MONITOR3_1 --size 1920x1080 --pos 1920x0 --rotate normal \
    --output $MONITOR3_2 --size 1920x1080 --pos 1920x0 --rotate normal

