#!/usr/bin/env bash


screenshot_file=/tmp/$(date +%s).png;
echo $screenshot_file > /tmp/screenshot_file; 
accent=$(cat /home/bresilla/.cache/wal/colors | head -2 | tail -1)

if [[ $1 == "--grim" ]]; then
    grim -g "$(slurp)" $screenshot_file
    wl-copy < $screenshot_file
    sxiv $screenshot_file
elif [[ $1 == "--maim" ]]; then
    maim -u -s | tee $screenshot_file | xclip -sel clip -t image/png -i
elif [[ $1 == "--ocr" ]]; then
    TEXT_FILE="/tmp/ocr.txt"
    IMAGE_FILE="/tmp/ocr.png"
    if [[ $2 == "--x11" ]]; then
        maim -u -s | tee $IMAGE_FILE | xclip -sel clip -t image/png -i
        tesseract "$IMAGE_FILE" "${TEXT_FILE//\.txt/}" 2> /dev/null
        sed -i 's/\x0c//' "$TEXT_FILE"
        NUM_LINES=$(wc -l < $TEXT_FILE)
        if [ "$NUM_LINES" -eq 0 ]; then
            exit 1
        fi
        xclip -selection clip < "$TEXT_FILE"
    elif [[ $2 == "--way" ]]; then
        grim -g "$(slurp)" $IMAGE_FILE
        tesseract "$IMAGE_FILE" "${TEXT_FILE//\.txt/}" 2> /dev/null
        sed -i 's/\x0c//' "$TEXT_FILE"
        NUM_LINES=$(wc -l < $TEXT_FILE)
        if [ "$NUM_LINES" -eq 0 ]; then
            exit 1
        fi
        wl-copy < "$TEXT_FILE"
        echo 0
    fi
    rm "$TEXT_FILE"
    rm "$IMAGE_FILE"
fi

adb push $screenshot_file /sdcard/From_Skynet

# sxiv $screenshot_file &
