#!/usr/bin/env bash


screenshot_file=/tmp/$(date +%s).png;
echo $screenshot_file > /tmp/screenshot_file; 
accent=$(cat /home/bresilla/.cache/wal/colors | head -2 | tail -1)

if [[ $1 == "--flame" ]]; then
    flameshot config -m "$accent"
    flameshot gui -p /tmp --raw > $screenshot_file || exit
elif [[ $1 == "--maim" ]]; then
    maim -u -s | tee $screenshot_file | xclip -sel clip -t image/png -i
fi

adb push $screenshot_file /sdcard/From_Skynet

# sxiv $screenshot_file &
