#!/usr/bin/env bash

rm $HOME/.fehbg &
rm $HOME/.lyxauth &
rm $HOME/.wget-hstsr &
rm $HOME/.Xauthority &
rm -r $HOME/.lldb &
rm -r $HOME/.fltk &
rm -r $HOME/.dbus &
rm -r $HOME/.conda &
rm -r $HOME/.pki &
rm -r $HOME/.vnc &
rm -r $HOME/.gnupg &
