# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
keyboard_layout:
  layout: "us"

# evdev_modifier_delay: 20
backend: Clipboard

matches:
  # Simple text replacement
  - trigger: ":euro"
    replace: "€"

  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":phone"
    replace: "0031628022776"

  - trigger: ":hr"
    replace: "----------------------------------------------------------------------------"

  # Dates
  - trigger: ":udate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: "date"
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":bang"
    replace: "#!/bin/bash"
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  - trigger: ":wur"
    replace: "trim.bresilla@wur.nl"
  - trigger: ":hotmail"
    replace: "kushtrim.bresilla@hotmail.com"
  - trigger: ":gmail"
    replace: "kushtrim.bresilla@gmail.com"
  - trigger: ":yahoo"
    replace: "kushtrim.bresilla@yahoo.com"
