#!/usr/bin/env python3

import can
from can.interface import Bus
from can.io.asc import ASCReader

can.rc['interface'] = 'socketcan'
can.rc['channel'] = 'vcan0'
can.rc['bitrate'] = 500000

bus = Bus()


readerr = ASCReader("/doc/docs/WUR/data/R4C/logs/Sprayer_AllData2022-06-30_18-44-38.asc")
for elem in readerr:
    bus.send(elem)
