#! /bin/bash

BAUD=8
DEV=can0

# Detect correct port for device interfaces
TERM_PORT=$(ls -l /dev/serial/by-id/ | grep 1fc9_00a3 | sed 's/.*\///g' | awk '{if(NR==2) print $0}')
CANB_PORT=$(ls -l /dev/serial/by-id/ | grep 1fc9_00a3 | sed 's/.*\///g' | awk '{if(NR==1) print $0}')


echo "Terminal interface on: $TERM_PORT"
echo "CAN Bus  interface on: $CANB_PORT"

# Set the mode to slcan
chmod a+rw /dev/$TERM_POR
echo -ne "set can-mode slcan" > /dev/$TERM_PORT

echo "Attaching slcan device..."

# Attach to the port with slcand
slcand -s$BAUD -o /dev/"$CANB_PORT" $DEV

# Give interface time to come up
sleep .25

# Enable the inteface
ifconfig $DEV up
ifconfig $DEV txqueuelen 1000

echo "Interface is enabled."

# Turn up the inteface
ip link set dev $DEV up

echo "Interface is UP."
