#!/bin/bash
# Load the kernel module.
modprobe vcan

# Create the virtual CAN interface.
ip link add name vcan0 type vcan
# For CAN-FD
ip link set vcan0 mtu 72
# Bring the virutal CAN interface online
ip link set dev vcan0 up
