#!/usr/bin/env bash

if [ $# -eq 0 ]
  then
    echo "No arguments supplied, exiting..."
    exit 1
fi


ip route add 0.0.0.0 via 192.168.1.1
iptables -t nat -A POSTROUTING -o $1 -j MASQUERADE
iptables -A FORWARD -i eth1 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i wlan0 -o $1 -j ACCEPT

iptables -t nat -A POSTROUTING -s 192.168.1.1/24 -j SNAT --to-source 192.168.1.10

iptables-save -t nat
