#!/bin/bash
source ~/.cache/wal/colors.sh
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -theme-str "*{accent: ${color1:-#FFFFFF}; bckgrd: ${color0:-#000000};}")

rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p ">>>"
