#!/bin/bash

WORDLIST="$HOME/.config/dict/wordlist.txt"
ADJECTIVELIST="$HOME/.config/dict/adjective.txt"
NOUNLIST="$HOME/.config/dict/noun.txt"

fancy=$(shuf -n1 $ADJECTIVELIST)"_"$(shuf -n1 $NOUNLIST)

printf $fancy | xclip  -sel clip
echo $fancy


