#!/usr/bin/env bash

pactl set-card-profile alsa_card.pci-0000_00_1f.3 off

sleep 5

pactl set-card-profile alsa_card.pci-0000_00_1f.3 output:analog-stereo+input:analog-stereo

# pactl set-default-sink bluez_output.F8_4E_17_6F_48_4B.a2dp-sink

# pactl set-default-source bluez_output.F8_4E_17_6F_48_4B.a2dp-sink.monitor
