#!/bin/bash

BLUE='\033[0;34m'; GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'

USR=$(echo $1 | cut -d@ -f1)
IPP=$(echo $1 | cut -d@ -f2)
KEY=$(gpg --export-ssh-key 90C641170CDAEA9E)

ssh $USR@$IPP "echo $KEY >> /home/$USR/.ssh/author"

printf "\nkey: ${BLUE}$KEY${NC} \nexported to: ${GREEN}$IPP${NC} for user: ${GREEN}$USR${NC}\n"
