#!/bin/bash

echo -n 'Password: ' >&2
read -s _UNLOCK_PASSWORD || return
# echo $_UNLOCK_PASSWORD
killall -q -u "$(whoami)" gnome-keyring-daemon
eval $(echo -n "${_UNLOCK_PASSWORD}" | gnome-keyring-daemon --daemonize --login | sed -e 's/^/export /')
unset _UNLOCK_PASSWORD
echo '' >&2

