#!/bin/bash
adb reverse tcp:5900 tcp:5900
gtf 2000 1200 60
xrandr --newmode "2000x1200_60.00"  201.50  2000 2136 2352 2704  1200 1201 1204 1242  -HSync +Vsync
xrandr --addmode VIRTUAL1 "2000x1200_60.00"


MONITOR1=DP1
MONITOR2=DVI-I-2-1
MONITOR3=DVI-I-3-2
MONITOR4=VIRTUAL1
xrandr --output $MONITOR1 --primary --mode 3456x2160 --pos 186x1080 --rotate normal \
    --output $MONITOR4 --mode 1920x1080 --pos 3456x495 --rotate normal \
    --output $MONITOR2 --mode 1920x1080 --pos 1920x0 --rotate normal \
    --output $MONITOR3 --mode 1920x1080 --pos 0x0 --rotate normal \
    --output DP1 --off --output DP2 --off --output DP3 --off &

xrandr

x11vnc -display :0 -clip 2000x1200+3456+495 -rfbport 5900

