#!/usr/bin/env bash

packages=("
  opencv 
  numpy
  pillow
  scipy
  tqdm
  pyyaml
  matplotlib
  tensorboard
  scikit-learn
  scikit-image
  pandas
  seaborn
  python-lsp-server
  ipython
  ipykernel
  mlxtend
  torchmetrics
  onnx
  onnxruntime 
  kaggle
")

echo $packages
