label = "rust"
name = "rust"

[[file]]
  destination = ".editorconfig"
  template = "rust/.editorconfig"

[[file]]
  destination = ".envrc"
  template = "rust/.envrc"

[[file]]
  destination = ".travis.yml"
  template = "cmake/.travis.yml"

[[file]]
  destination = "AUTHORS.md"
  template = "AUTHORS.md"

[[file]]
  destination = "CHANGELOG.md"
  template = "CHANGELOG.md"

[[file]]
  destination = "CONTRIBUTING.md"
  template = "CONTRIBUTING.md"

[[file]]
  destination = "CONDUCT.md"
  template = "CONDUCT.md"

[[file]]
  destination = "LICENSE.md"
  template = "LICENSE.md"

[[file]]
  destination = "README.md"
  template = "README.md"

[[file]]
  destination = "shell.nix"
  template = "rust/shell.nix"

[[folder]]
  destination = ".github/"
  template = "rust/.github"

[[folder]]
  destination = ".vscode/"
  template = "rust/.vscode"


[[script]]
  name = "rust.sh"
  type = "post"
  runAsSudo = false
  execNumber = 1

[[script]]
  name = "readme.sh"
  type = "post"
  runAsSudo = false
  execNumber = 2

[[script]]
  name = "direnv.sh"
  type = "post"
  runAsSudo = false
  execNumber = 3

[[script]]
  name = "git.sh"
  type = "post"
  runAsSudo = false
  execNumber = 4
