folder = []
label = "hugo"
name = "website"

[[file]]
  destination = ".envrc"
  template = "py/.envrc"

[[file]]
  destination = "AUTHORS.md"
  template = "AUTHORS.md"

[[file]]
  destination = "LICENSE.md"
  template = "LICENSE.md"

[[file]]
  destination = "README.md"
  template = "README.md"

[[file]]
  destination = "shell.nix"
  template = "py/shell.nix"

[[script]]
  name = "hugo.sh"
  type = "post"
  runAsSudo = false
  execNumber = 1

[[script]]
  name = "readme.sh"
  type = "post"
  runAsSudo = false
  execNumber = 2

[[script]]
  name = "direnv.sh"
  type = "post"
  runAsSudo = false
  execNumber = 3

[[script]]
  name = "git.sh"
  type = "post"
  runAsSudo = false
  execNumber = 4
