label = "python"
name = "python"

[[file]]
  destination = ".envrc"
  template = "py/.envrc"

[[file]]
  destination = ".gitignore"
  template = "py/.gitignore"

[[file]]
  destination = "AUTHORS.md"
  template = "AUTHORS.md"

[[file]]
  destination = "CHANGELOG.md"
  template = "CHANGELOG.md"

[[file]]
  destination = "CONTRIBUTING.md"
  template = "CONTRIBUTING.md"

[[file]]
  destination = "CONDUCT.md"
  template = "CONDUCT.md"

[[file]]
  destination = "LICENSE.md"
  template = "LICENSE.md"

[[file]]
  destination = "README.md"
  template = "README.md"

[[file]]
  destination = "shell.nix"
  template = "py/shell.nix"

[[folder]]
  destination = "src/"
  template = ""

[[script]]
  name = "anaconda.sh"
  type = "post"
  runAsSudo = false
  execNumber = 1

[[script]]
  name = "readme.sh"
  type = "post"
  runAsSudo = false
  execNumber = 2

[[script]]
  name = "direnv.sh"
  type = "post"
  runAsSudo = false
  execNumber = 3

[[script]]
  name = "git.sh"
  type = "post"
  runAsSudo = false
  execNumber = 4
