label = "go"
name = "go"

[[file]]
  destination = ".editorconfig"
  template = "go/.editorconfig"

[[file]]
  destination = ".envrc"
  template = "go/.envrc"

[[file]]
  destination = ".travis.yml"
  template = "cmake/.travis.yml"

[[file]]
  destination = "AUTHORS.md"
  template = "AUTHORS.md"

[[file]]
  destination = "CHANGELOG.md"
  template = "CHANGELOG.md"

[[file]]
  destination = "CONTRIBUTING.md"
  template = "CONTRIBUTING.md"

[[file]]
  destination = "CONDUCT.md"
  template = "CONDUCT.md"

[[file]]
  destination = "LICENSE.md"
  template = "LICENSE.md"

[[file]]
  destination = "README.md"
  template = "README.md"

[[file]]
  destination = "shell.nix"
  template = "go/shell.nix"

[[folder]]
  destination = ".github/"
  template = "go/.github"

[[folder]]
  destination = ".vscode/"
  template = "go/.vscode"

[[folder]]
  destination = "source/"
  template = "go/source"

[[script]]
  name = "go.sh"
  type = "post"
  runAsSudo = false
  execNumber = 1

[[script]]
  name = "readme.sh"
  type = "post"
  runAsSudo = false
  execNumber = 2

[[script]]
  name = "direnv.sh"
  type = "post"
  runAsSudo = false
  execNumber = 3

[[script]]
  name = "git.sh"
  type = "post"
  runAsSudo = false
  execNumber = 4
