folder = []
label = "tex"
name = "latex"

[[file]]
  destination = ".envrc"
  template = "tex/.envrc"

[[file]]
  destination = ".gitignore"
  template = "tex/.gitignore"

[[file]]
  destination = "AUTHORS.md"
  template = "AUTHORS.md"

[[file]]
  destination = "LICENSE.md"
  template = "LICENSE.md"

[[file]]
  destination = "README.md"
  template = "README.md"

[[file]]
  destination = "article.tex"
  template = "tex/article.tex"

[[file]]
  destination = "bibliography.bib"
  template = "tex/bibliography.bib"

[[script]]
  name = "readme.sh"
  type = "post"
  runAsSudo = false
  execNumber = 2

[[script]]
  name = "direnv.sh"
  type = "post"
  runAsSudo = false
  execNumber = 3

[[script]]
  name = "git.sh"
  type = "post"
  runAsSudo = false
  execNumber = 4
