#! /bin/sh
###PROFILE
source /home/bresilla/.profile

###############################################################################################################################
#|||	SETTINGS
###############################################################################################################################
bspc config border_width         2
bspc config normal_border_color "#000000"
bspc config focused_border_color "#FFFFFF"
bspc config active_border_color "#000000"
bspc config presel_feedback_color "#575757"
bspc config window_gap          10
bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true
bspc config pointer_follows_monitor true
bspc config auto_alternate true
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

###############################################################################################################################
#|||	WORKSPACES & MONITORS
###############################################################################################################################

# bspc monitor $MONITOR1 -d 1 2 3 4 5
# bspc monitor $MONITOR2 -d 1 2 3 4 5

###############################################################################################################################
#|||	ASSIGNMENTS
###############################################################################################################################
bspc rule -a kitty state=floating sticky
bspc rule -a cool-retro-term state=floating sticky
bspc rule -a til state=tiled
bspc rule -a feh state=floating
bspc rule -a sxiv state=floating
bspc rule -a mpv state=floating
bspc rule -a scrcpy state=floating
bspc rule -a MPlayer state=floating
bspc rule -a matplotlib state=floating
bspc rule -a URxvt state=floating
bspc rule -a Oblogout state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a URxvt:launcher state=floating center sticky
bspc rule -a LAUNCHER state=floating center sticky
bspc rule -a Boomer state=fullscreen sticky
bspc rule -a Screenkey manage=off

###############################################################################################################################
#|||	SCRIPTS
###############################################################################################################################
/env/cpp/bin/btops &

# COLORS
/home/bresilla/dots/.func/wm/rainbow regen &

#MONITORS
MONITOR1=eDP-1
MONITOR2=DP-1
xrandr --output $MONITOR1 --primary --mode 3840x2160 --pos 0x2160 --rotate normal --output $MONITOR2 --mode 3840x2160 --pos 0x0 --rotate normal --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off &

#TASKBAR
/home/bresilla/.config/polybar/poly &

#SHORTCUTS
pkill sxhkd
while pgrep -x sxhkd >/dev/null; do sleep 1; done
sxhkd -c /home/bresilla/.config/sxhkd/sxhkdrc &


#KEYBOARD
xset -r 118 & #Insert
xset -r 107 & #Print
