#!/usr/bin/env sh


blackTX="#[fg=colour0]"
blackBG="#[bg=colour0]"
whiteTX="#[fg=colour15]"
whiteBG="#[bg=colour15]"
accentTX="#[fg=colour1]"
accentBG="#[bg=colour1]"
orangeBG="#[bg=colour208]"
orangeTX="#[fg=colour208]"
redBG="#[bg=colour124]"
redTX="#[fg=colour124]"
greenBG="#[bg=colour40]"
greenTX="#[fg=colour40]"
grayBG="#[bg=colour7]"
grayTX="#[fg=colour7]"
defaBG="#[bg=default]"
defaTX="#[fg=default]"
BLD="#[bold]"
NLD="#[nobold]"

cpu=$(/home/bresilla/.config/tmux/modules/cpu-stat)
netspeed=$(/home/bresilla/.config/tmux/modules/netwidth)
mem=$(free | grep Mem | awk '{print (100 - ($4/($3+$4) * 100.0));}')
bat=$(acpi | awk '{print $4}' | tr -d '%,')
chrg=$(acpi | awk '{print $3}' | tr -d '%,')
tmu=$(date +"%H:%M")
dat=$(date +"%d.%m.%G")
upt=$(uptime -p)
net=$(if nc -zw1 google.com 443; then echo "$blackTX●"; else echo "$redTX●"; fi)
wat=$(echo - | awk "{printf \"%.1f\", $(($(cat /sys/class/power_supply/BAT0/current_now) * $(cat /sys/class/power_supply/BAT0/voltage_now))) / 1000000000000 }")

[[ $bat -le 10 ]] && grayBG=$redBG whiteTX=$redTX accentBG=$redBG accentTX=$redTX

cpu=${cpu%.*}
mem=${mem%.*}
mem="$greyTX$greyBG $blackTX$mem% "


battery="$redTX  $BLD$blackTX$bat%$NLD "
[[ "$chrg" != "Discharging" ]] && battery="$blackTX  $BLD$blackTX$bat%$NLD "

spacer="$blackTX$blackBG"

if (( cpu > 80 )); then
    proc="$redTX$blackTX$redBG $BLD$cpu% "
elif (( cpu > 50 )); then
    proc="$orangeTX$blackTX$orangeBG $BLD$cpu% "
else
    proc="$whiteTX$whiteBG $blackTX$cpu% "
fi

RIGHT_STATUS="$proc$mem$spacer$accentTX$accentBG$battery"
LEFT_STATUS="$accentBG$blackTX $BLD$tmu$NLD $net$accentTX$whiteBG$blackTX $dat $whiteTX$defaBG$grayTX $upt"

if [ "$1" == "RIGHT" ] ;then
    echo $RIGHT_STATUS
elif [ "$1" == "LEFT" ] ;then
    echo $LEFT_STATUS
fi
