#!/usr/bin/env sh

cpu=$(/home/bresilla/.config/tmux/modules/cpu-stat)
netspeed=$(/home/bresilla/.config/tmux/modules/netwidth)
mem=$(free | grep Mem | awk '{print (100 - ($4/($3+$4) * 100.0));}')
bat=$(acpi | awk '{print $4}' | tr -d '%,')
chrg=$(acpi | awk '{print $3}' | tr -d '%,')
tmu=$(date | awk '{print $5}' | cut -d: -f1,2)
upt=$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}')
wat=$(echo - | awk "{printf \"%.1f\", $(($(cat /sys/class/power_supply/BAT0/current_now) * \
  $(cat /sys/class/power_supply/BAT0/voltage_now))) / 1000000000000 }")

cpu=${cpu%.*}
mem=${mem%.*}

blackTX="#[fg=colour0]"
blackBG="#[bg=colour0]"
whiteTX="#[fg=colour15]"
whiteBG="#[bg=colour15]"
accentTX="#[fg=colour1]"
accentBG="#[bg=colour1]"
orangeBG="#[bg=colour208]"
orangeTX="#[fg=colour208]"
redBG="#[bg=colour124]"
redTX="#[fg=colour124]"
greenBG="#[bg=colour40]"
greenTX="#[fg=colour40]"
grayBG="#[bg=colour244]"
grayTX="#[fg=colour244]"
defaBG="#[bg=default]"
defaTX="#[fg=default]"
BLD="#[bold]"
NLD="#[nobold]"

[[ $bat -le 10 ]] && grayBG=$redBG whiteTX=$redTX accentBG=$redBG accentTX=$redTX

if [ $(cat /proc/acpi/bbswitch | awk 'NF>1{print $NF}') == ON ]; then
    power="$grayTX $redTX$BLD$wat W $NLD"
else
    power="$grayTX $wat W "
fi

battery="$redTX  $blackTX$bat% $whiteTX$defaBG"
[[ "$chrg" != "Discharging" ]] && battery="$blackTX  $blackTX$bat% $whiteTX$defaBG"

memo="$greyTX$greyBG $blackTX$mem% "
spacer="$blackTX$blackBG"

if (( cpu > 80 )); then
    proc="$redTX$blackTX$redBG $BLD$cpu% "
elif (( cpu > 50 )); then
    proc="$orangeTX$blackTX$orangeBG $BLD$cpu% "
else
    proc="$whiteTX$whiteBG $blackTX$cpu% "
fi
network="$accentTX$accentBG $blackTX$netspeed$accentBG "

RIGHT_STATUS="$power$proc$memo$spacer$network"

main="$accentBG$blackTX $tmu $accentTX$whiteBG"

cdr="$grayTX"
LEFT_STATUS="$main$battery$cdr"

if [ "$1" == "RIGHT" ] ;then
    echo $RIGHT_STATUS
elif [ "$1" == "LEFT" ] ;then
    echo $LEFT_STATUS
fi
