[scripts.modmap]
alias = 'modmap'
command = 'xmodmap /home/bresilla/.Xmodmap'

[scripts.pio]
alias = 'pio'
command = 'eval "$(_PIO_COMPLETE=zsh_source pio)"'

[scripts.reload_d]
alias = 'reload_d'
command = 'doas systemctl daemon-reload'

[scripts.reload_u]
alias = 'reload_u'
command = 'systemctl --user daemon-reload'

[scripts.resound]
alias = 'resound'
command = 'pactl set-card-profile alsa_card.pci-0000_00_1f.3 off && sleep 5 && pactl set-card-profile alsa_card.pci-0000_00_1f.3 output:analog-stereo+input:analog-stereo'

[scripts.wifisel]
alias = 'wifisel'
command = 'iwctl station wlan0 connect $(iwctl station wlan0 scan && sleep 4 && iwctl station wlan0 get-networks | tail -n -3 | fzf | choose 0)'

[default]
