#!/bin/sh

connection_status=$(doas wg show wg0 2>/dev/null | head -n 1 | awk '{print $NF }')

case "$1" in
--toggle)
    if [ "$connection_status" = "wg0" ]; then
        doas wg-quick down wg0 2>/dev/null
    else
        doas wg-quick up wg0 2>/dev/null
    fi
    ;;
*)
    if [ "$connection_status" = "wg0" ]; then
        echo "UP"
    else
        echo "DOWN"
    fi
    ;;
esac

